# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4000)),
                ('pretty_name', models.CharField(max_length=4000)),
                ('paging_next', models.CharField(max_length=4000)),
                ('access_token', models.CharField(max_length=4500)),
            ],
        ),
    ]
