# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas_facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInsights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('end_time', models.DateTimeField()),
                ('period', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=4500)),
                ('description', models.CharField(max_length=4500)),
                ('name', models.CharField(max_length=4500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estatisticas_facebook.Page')),
            ],
        ),
    ]
