# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas_facebook', '0002_pageinsights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinsights',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageinsights',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
