# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas_facebook', '0003_auto_20171031_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='access_token',
            field=models.CharField(blank=True, max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='paging_next',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='pretty_name',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
