# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_de_compra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_de_parcelas', models.IntegerField()),
                ('data_de_compra', models.DateField()),
                ('preco_de_venda', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_de_venda', models.DateField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindles.Modelo')),
            ],
        ),
    ]
