# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negociacao',
            name='data_de_compra',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='negociacao',
            name='data_de_venda',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='negociacao',
            name='numero_de_parcelas',
            field=models.IntegerField(default=1),
        ),
    ]
